import type { ValidationResult } from './openai-service';
import type { ComprehensiveVisaRequirements } from './visa-requirements-service';

interface ReportData {
  validationResults: ValidationResult;
  personalInfo: any;
  country: string;
  visaType: string;
  nationality: string;
  requirements?: ComprehensiveVisaRequirements;
  uploadedDocuments: any[];
}

export function generateValidationReportMarkdown(data: ReportData): string {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `# Visa Document Validation Report

**Generated:** ${currentDate}  
**Destination:** ${data.country}  
**Visa Type:** ${data.visaType}  
**Session ID:** VV-${Date.now()}

---

## Applicant Information

| Field | Value |
|-------|-------|
| **Name** | ${data.personalInfo.firstName || ''} ${data.personalInfo.lastName || ''} |
| **Nationality** | ${data.nationality} |
| **Passport Number** | ${data.personalInfo.passportNumber || 'Not provided'} |
| **Date of Birth** | ${data.personalInfo.dateOfBirth || 'Not provided'} |
| **Travel Date** | ${data.personalInfo.travelDate ? new Date(data.personalInfo.travelDate).toLocaleDateString() : 'Not provided'} |
| **Stay Duration** | ${data.personalInfo.stayDuration || 'Not specified'} days |

---

## Validation Score

### Overall Assessment: **${data.validationResults.score}%**

${data.validationResults.score === 0 ? 
  '⚠️ **CRITICAL**: Missing required documents - Visa application incomplete' :
  data.validationResults.score >= 90 ? 
    '✅ **EXCELLENT**: Documents appear complete and properly formatted' :
    data.validationResults.score >= 75 ?
      '✅ **GOOD**: Documents mostly complete with minor issues' :
      '⚠️ **NEEDS ATTENTION**: Several issues need to be addressed'
}

---

## Verified Documents

${data.validationResults.verified.length > 0 ? 
  data.validationResults.verified.map(item => `✅ **${item.type}**: ${item.message}`).join('\n') :
  'No documents have been verified yet.'
}

---

## Issues Found

${data.validationResults.issues.length > 0 ? 
  data.validationResults.issues.map(issue => `
### ⚠️ ${issue.title}

**Category:** ${issue.type}  
**Description:** ${issue.description}  
**Recommendation:** ${issue.recommendation}
`).join('\n') :
  '✅ No issues found in the uploaded documents.'
}

---

## Uploaded Documents

${data.uploadedDocuments.length > 0 ?
  data.uploadedDocuments.map((doc, index) => `
${index + 1}. **${doc.originalName}**
   - **Type:** ${doc.analysis?.documentType || 'Unknown'}
   - **Status:** ${doc.status}
   - **Confidence:** ${doc.analysis?.confidence ? Math.round(doc.analysis.confidence * 100) + '%' : 'N/A'}
   ${doc.analysis?.issuingCountry ? `- **Issuing Country:** ${doc.analysis.issuingCountry}` : ''}
   ${doc.analysis?.expirationDate ? `- **Expiration:** ${doc.analysis.expirationDate}` : ''}
`).join('\n') :
  'No documents uploaded yet.'
}

---

## Report Summary

**Completion Status:** ${data.validationResults.score}% Complete  
**Generated:** ${data.validationResults.completedAt}  
**Next Steps:** ${data.validationResults.issues.length > 0 ? 'Address the issues listed above before submitting your visa application.' : 'Your documents appear ready for visa application submission.'}

---

*Generated by VisaValidator Requirements System*  
*© 2024 VisaValidator - All rights reserved*

**Need Help?** Contact the official embassy or consulate for the most current requirements and assistance with your application.
`;
}

export function generateRequirementsChecklistMarkdown(requirements: ComprehensiveVisaRequirements): string {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long', 
    day: 'numeric'
  });

  return `# Visa Requirements Checklist

**Country:** ${requirements.country}  
**Visa Type:** ${requirements.visaType}  
**Last Updated:** ${requirements.lastUpdated}  
**Generated:** ${currentDate}

---

## Required Documents

${requirements.requirements
  .filter(req => req.required)
  .map((req, index) => `
### ${index + 1}. ${req.title} ${req.required ? '(REQUIRED)' : '(OPTIONAL)'}

**Description:** ${req.description}

${req.formats && req.formats.length > 0 ? `**Accepted Formats:** ${req.formats.join(', ')}` : ''}

${req.specificNotes && req.specificNotes.length > 0 ? `
**Important Notes:**
${req.specificNotes.map(note => `- ${note}`).join('\n')}` : ''}

${req.processingTime ? `**Processing Time:** ${req.processingTime}` : ''}

${req.additionalInfo ? `**Additional Information:** ${req.additionalInfo}` : ''}

---
`).join('')}

## General Information

**Processing Time:** ${requirements.generalInfo.processingTime}  
**Visa Validity:** ${requirements.generalInfo.validity}  
**Fees:** ${requirements.generalInfo.fees}  
**Application Methods:** ${requirements.generalInfo.applicationMethods.join(', ')}

---

## Important Notes

${requirements.importantNotes.map(note => `- ${note}`).join('\n')}

${requirements.recentChanges && requirements.recentChanges.length > 0 ? `
---

## Recent Changes

${requirements.recentChanges.map(change => `- ${change}`).join('\n')}
` : ''}

---

## Official Sources

For the most current and detailed information, please visit:

${requirements.officialSources.map(source => `- ${source}`).join('\n')}

---

*Generated by VisaValidator Requirements System*  
*Last updated: ${requirements.lastUpdated}*

**Disclaimer:** This checklist is for guidance only. Always verify requirements with official sources before applying.
`;
}