import React from 'react';

interface FlagIconRealProps {
  country: string;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

// 🚀 Country code mapping for flag-icons CSS
const COUNTRY_CODES: Record<string, string> = {
  'afghanistan': 'af',
  'albania': 'al',
  'algeria': 'dz',
  'andorra': 'ad',
  'angola': 'ao',
  'argentina': 'ar',
  'armenia': 'am',
  'australia': 'au',
  'austria': 'at',
  'azerbaijan': 'az',
  'bahrain': 'bh',
  'bangladesh': 'bd',
  'belarus': 'by',
  'belgium': 'be',
  'belize': 'bz',
  'benin': 'bj',
  'bhutan': 'bt',
  'bolivia': 'bo',
  'bosnia': 'ba',
  'botswana': 'bw',
  'brazil': 'br',
  'brunei': 'bn',
  'bulgaria': 'bg',
  'burkina-faso': 'bf',
  'burundi': 'bi',
  'cambodia': 'kh',
  'cameroon': 'cm',
  'canada': 'ca',
  'cape-verde': 'cv',
  'chad': 'td',
  'chile': 'cl',
  'china': 'cn',
  'colombia': 'co',
  'comoros': 'km',
  'congo': 'cg',
  'costa-rica': 'cr',
  'croatia': 'hr',
  'cuba': 'cu',
  'cyprus': 'cy',
  'czech-republic': 'cz',
  'denmark': 'dk',
  'djibouti': 'dj',
  'dominican-republic': 'do',
  'ecuador': 'ec',
  'egypt': 'eg',
  'el-salvador': 'sv',
  'estonia': 'ee',
  'eswatini': 'sz',
  'ethiopia': 'et',
  'fiji': 'fj',
  'finland': 'fi',
  'france': 'fr',
  'gabon': 'ga',
  'gambia': 'gm',
  'georgia': 'ge',
  'germany': 'de',
  'ghana': 'gh',
  'greece': 'gr',
  'guatemala': 'gt',
  'guinea': 'gn',
  'guyana': 'gy',
  'haiti': 'ht',
  'honduras': 'hn',
  'hungary': 'hu',
  'iceland': 'is',
  'india': 'in',
  'indonesia': 'id',
  'iran': 'ir',
  'iraq': 'iq',
  'ireland': 'ie',
  'israel': 'il',
  'italy': 'it',
  'ivory-coast': 'ci',
  'jamaica': 'jm',
  'japan': 'jp',
  'jordan': 'jo',
  'kazakhstan': 'kz',
  'kenya': 'ke',
  'kuwait': 'kw',
  'kyrgyzstan': 'kg',
  'laos': 'la',
  'latvia': 'lv',
  'lebanon': 'lb',
  'lesotho': 'ls',
  'liberia': 'lr',
  'libya': 'ly',
  'lithuania': 'lt',
  'luxembourg': 'lu',
  'madagascar': 'mg',
  'malawi': 'mw',
  'malaysia': 'my',
  'maldives': 'mv',
  'mali': 'ml',
  'malta': 'mt',
  'mauritania': 'mr',
  'mauritius': 'mu',
  'mexico': 'mx',
  'moldova': 'md',
  'monaco': 'mc',
  'mongolia': 'mn',
  'montenegro': 'me',
  'morocco': 'ma',
  'mozambique': 'mz',
  'myanmar': 'mm',
  'namibia': 'na',
  'nepal': 'np',
  'netherlands': 'nl',
  'new-zealand': 'nz',
  'nicaragua': 'ni',
  'niger': 'ne',
  'nigeria': 'ng',
  'north-korea': 'kp',
  'north-macedonia': 'mk',
  'norway': 'no',
  'oman': 'om',
  'pakistan': 'pk',
  'panama': 'pa',
  'papua-new-guinea': 'pg',
  'paraguay': 'py',
  'peru': 'pe',
  'philippines': 'ph',
  'poland': 'pl',
  'portugal': 'pt',
  'qatar': 'qa',
  'romania': 'ro',
  'russia': 'ru',
  'rwanda': 'rw',
  'samoa': 'ws',
  'san-marino': 'sm',
  'saudi-arabia': 'sa',
  'senegal': 'sn',
  'serbia': 'rs',
  'seychelles': 'sc',
  'sierra-leone': 'sl',
  'singapore': 'sg',
  'slovakia': 'sk',
  'slovenia': 'si',
  'solomon-islands': 'sb',
  'somalia': 'so',
  'south-africa': 'za',
  'south-korea': 'kr',
  'south-sudan': 'ss',
  'spain': 'es',
  'sri-lanka': 'lk',
  'sudan': 'sd',
  'suriname': 'sr',
  'sweden': 'se',
  'switzerland': 'ch',
  'syria': 'sy',
  'taiwan': 'tw',
  'tajikistan': 'tj',
  'tanzania': 'tz',
  'thailand': 'th',
  'timor-leste': 'tl',
  'togo': 'tg',
  'tonga': 'to',
  'trinidad-tobago': 'tt',
  'tunisia': 'tn',
  'turkey': 'tr',
  'turkmenistan': 'tm',
  'uganda': 'ug',
  'ukraine': 'ua',
  'uae': 'ae',
  'uk': 'gb',
  'usa': 'us',
  'uruguay': 'uy',
  'uzbekistan': 'uz',
  'vanuatu': 'vu',
  'vatican': 'va',
  'venezuela': 've',
  'vietnam': 'vn',
  'yemen': 'ye',
  'zambia': 'zm',
  'zimbabwe': 'zw'
};

const sizeClasses = {
  sm: 'text-sm',
  md: 'text-base',
  lg: 'text-xl'
};

export default function FlagIconReal({ country, size = 'md', className = '' }: FlagIconRealProps) {
  const countryCode = COUNTRY_CODES[country.toLowerCase()];
  const sizeClass = sizeClasses[size];

  if (!countryCode) {
    return <span className={`inline-block ${sizeClass} ${className}`}>🌍</span>;
  }

  return (
    <span
      className={`fi fi-${countryCode} ${sizeClass} ${className}`}
      style={{
        fontSize: size === 'sm' ? '1rem' : size === 'md' ? '1.25rem' : '1.5rem',
        lineHeight: 1,
        backgroundSize: 'contain',
        backgroundPosition: '50%',
        backgroundRepeat: 'no-repeat'
      }}
    />
  );
}